project:
  render:
    - index.qmd
    - research.qmd
    - projects.qmd
    - publications.qmd
    - conferences.qmd
    - teaching.qmd

website:
  navbar:
    left:
      - href: research.qmd
        text: Research

      - href: projects.qmd
        text: Projects

      - href: publications.qmd
        text: Publications

      - href: conferences.qmd
        text: Conferences

      - href: teaching.qmd
        text: Teaching

      - href: cv.pdf
        text: CV

format:
  html:
    include-after-body: nav-menu.html
