project:
  type: website
  resources:
    - cv.pdf
    - googleb5e71a886e230686.html

profile:
  default: local

website:
  title: "Lisa Cuneo"
  site-url: "https://lisacuneo.github.io/"

  navbar:
    right:
      - icon: github
        href: https://github.com/LisaCuneo
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
